{
 "title": "5g sba",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Avg CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "        sum(rate(container_cpu_usage_seconds_total{name=~\"server.*\"}[30s])) by (name) *100\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "avg_response_time_milliseconds_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_response_time_milliseconds_total",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of UE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ue_load" }
   ]
  },
  {
   "title": "client_requests_received_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "client_requests_received_total", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "response_time_milliseconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_time_milliseconds_total",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "ue_loop_iteration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ue_loop_iteration" }
   ]
  }
 ]
}